services:
  official:
    image: rcdailey/zandronum-server:official-local
    build:
      context: .
      args:
        - REPO_URL=https://foss.heptapod.net/zandronum/zandronum-stable
        - REPO_TAG=ZA_3.2.1

  tspg:
    image: rcdailey/zandronum-server:tspg-local
    build:
      context: .
      args:
        - REPO_URL=http://hg.pf.osdn.net/view/d/do/doomjoshuaboy/zatspg-beta
        - REPO_TAG=TSPGv26
