services:
  official:
    image: rcdailey/zandronum-server:official-local
    build:
      context: .
      args:
        - DIST_DIR=dist/official

  tspg:
    image: rcdailey/zandronum-server:tspg-local
    build:
      context: .
      args:
        - DIST_DIR=dist/tspg
