# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # List these here so that they are used as display names in Github Actions Web UI
        image_tag_base: [official, tspg]
        include:
          - repo_url: https://hg.osdn.net/view/zandronum/zandronum-stable
            repo_tag: 4178904d7698 # there is no tag for 3.1
            image_tag_base: official
            image_tag_version: 3.1.0
          - repo_url: http://hg.pf.osdn.net/view/d/do/doomjoshuaboy/zatspg-beta
            repo_tag: TSPGv26
            image_tag_base: tspg
            image_tag_version: v31
    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v3
      -
        name: Docker QEmu Setup
        uses: docker/setup-qemu-action@v2
      -
        name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v2
      -
        name: Docker Login
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Docker Build & Push
        uses: docker/build-push-action@v3
        with:
          # Only publish new images when building the master branch
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            REPO_URL=${{ matrix.repo_url }}
            REPO_TAG=${{ matrix.repo_tag }}
          tags: |
            rcdailey/zandronum-server:${{ matrix.image_tag_base }}-latest
            rcdailey/zandronum-server:${{ matrix.image_tag_base }}-${{ matrix.image_tag_version }}
      -
        name: Update Repository Description
        uses: peter-evans/dockerhub-description@v3
        if: github.ref == 'refs/heads/master'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: rcdailey/zandronum-server
