# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # List these here so that they are used as display names in Github Actions Web UI
        image_tag_base: [official, tspg]
        include:
          - repo_url: https://foss.heptapod.net/zandronum/zandronum-stable
            repo_tag: ZA_3.2.1
            image_tag_base: official
            image_tag_version: 3.2.1
          - repo_url: http://hg.pf.osdn.net/view/d/do/doomjoshuaboy/zatspg-beta
            repo_tag: TSPGv26
            image_tag_base: tspg
            image_tag_version: v26
    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      -
        name: Docker QEmu Setup
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      -
        name: Docker Buildx Setup
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      -
        name: Docker Login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Docker Build & Push
        uses: docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47 # v6.19.1
        with:
          context: .
          # Only publish new images when building the master branch
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            REPO_URL=${{ matrix.repo_url }}
            REPO_TAG=${{ matrix.repo_tag }}
          cache-from: type=gha,scope=${{ matrix.image_tag_base }}
          cache-to: type=gha,mode=max,scope=${{ matrix.image_tag_base }}
          tags: |
            ${{ github.repository }}:${{ matrix.image_tag_base }}-latest
            ${{ github.repository }}:${{ matrix.image_tag_base }}-${{ matrix.image_tag_version }}
      -
        name: Update Repository Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ github.repository }}
